# Generated by Django 3.1.6 on 2021-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
