# Generated by Django 3.1.6 on 2021-09-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_auto_20210909_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dob',
            field=models.DateField(),
        ),
    ]
