# Generated by Django 3.1.6 on 2021-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_auto_20210910_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('parcel_type', models.CharField(max_length=30, null=True)),
                ('r_date', models.CharField(max_length=30, null=True)),
                ('gov_id', models.CharField(max_length=30, null=True)),
                ('gov_id_no', models.CharField(max_length=30, null=True)),
                ('parcel_weight', models.CharField(max_length=20, null=True)),
                ('parcel_distance', models.CharField(max_length=20, null=True)),
                ('sender_add', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
