# Generated by Django 3.1.6 on 2021-09-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_parcelrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelrequest',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
