# Generated by Django 3.1.6 on 2021-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_parcelrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiversDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20, null=True)),
                ('s_email', models.CharField(max_length=20, null=True)),
                ('r_name', models.CharField(max_length=20, null=True)),
                ('r_contact', models.CharField(max_length=20, null=True)),
                ('r_pin', models.CharField(max_length=20, null=True)),
                ('r_address', models.CharField(max_length=20, null=True)),
                ('r_state', models.CharField(max_length=20, null=True)),
                ('total_price', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
