# Generated by Django 3.1.6 on 2021-09-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_receiversdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiversdetail',
            old_name='s_email',
            new_name='parcel_id',
        ),
        migrations.RenameField(
            model_name='receiversdetail',
            old_name='s_name',
            new_name='parcel_msg',
        ),
        migrations.AddField(
            model_name='receiversdetail',
            name='sending_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
