# Generated by Django 3.1.6 on 2021-09-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0007_auto_20210920_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelrequest',
            name='parcel_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
