# Generated by Django 3.1.6 on 2021-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0008_parcelrequest_parcel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiversdetail',
            name='parcel_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
