# Generated by Django 3.1.6 on 2021-09-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0009_receiversdetail_parcel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20, null=True)),
                ('c_email', models.CharField(max_length=20, null=True)),
                ('c_contact', models.CharField(max_length=20, null=True)),
                ('c_msg', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20, null=True)),
                ('f_email', models.CharField(max_length=20, null=True)),
                ('f_contact', models.CharField(max_length=20, null=True)),
                ('f_msg', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
