# Generated by Django 4.0.1 on 2022-05-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0008_auto_20210529_2313'),
        ('courier', '0010_contact_feedback'),
    ]

    operations = [
    ]
