# Generated by Django 4.0.1 on 2022-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0012_delete_contact_delete_receiversdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=40, null=True)),
                ('month', models.CharField(max_length=40, null=True)),
                ('year', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
