# Generated by Django 4.0.1 on 2022-05-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0013_accountdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDetail',
        ),
    ]
