# Generated by Django 4.0.1 on 2022-05-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0014_delete_accountdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=40, null=True)),
                ('uname', models.CharField(max_length=40, null=True)),
                ('uemail', models.CharField(max_length=40, null=True)),
                ('contact', models.CharField(max_length=40, null=True)),
                ('amount', models.CharField(max_length=40, null=True)),
                ('dt', models.CharField(max_length=40, null=True)),
                ('mode', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
