# Generated by Django 4.0.1 on 2022-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0015_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cdate',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cno',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
