# Generated by Django 4.0.1 on 2022-05-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0016_payment_cdate_payment_cno'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
