# Generated by Django 4.0.1 on 2022-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0017_payment_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelrequest',
            name='test',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
