# Generated by Django 4.0.1 on 2022-05-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0018_parcelrequest_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dob',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
